(dp1
S'output'
p2
S"<type 'exceptions.TypeError'> 'Set' object is not iterable"
p3
sS'layer'
p4
S'/Users/rafihaque/Documents/cmps183/web2py/applications/hicappo/controllers/api.py'
p5
sS'code'
p6
S'<code object <module> at 0x10bf39130, file "/Users/rafihaque/Documents/cmps183/web2py/applications/hicappo/controllers/api.py", line 3>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/Users/rafihaque/Documents/cmps183/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/Users/rafihaque/Documents/cmps183/web2py/applications/hicappo/controllers/api.py", line 134, in <module>\n  File "/Users/rafihaque/Documents/cmps183/web2py/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/Users/rafihaque/Documents/cmps183/web2py/applications/hicappo/controllers/api.py", line 128, in find_temp_listings\n    for m in db(db.listing.id == r.listingid):\nTypeError: \'Set\' object is not iterable\n'
p11
s.