(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'int' object has no attribute 'strftime'"
p3
sS'layer'
p4
S'/Users/rafihaque/Documents/cmps183/web2py/applications/hicappo/controllers/api.py'
p5
sS'code'
p6
S'<code object <module> at 0x104815a30, file "/Users/rafihaque/Documents/cmps183/web2py/applications/hicappo/controllers/api.py", line 2>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/Users/rafihaque/Documents/cmps183/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/Users/rafihaque/Documents/cmps183/web2py/applications/hicappo/controllers/api.py", line 285, in <module>\n  File "/Users/rafihaque/Documents/cmps183/web2py/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/Users/rafihaque/Documents/cmps183/web2py/applications/hicappo/controllers/api.py", line 270, in payment_history_content\n    for_month = int(r.for_month).strftime("%B"),\nAttributeError: \'int\' object has no attribute \'strftime\'\n'
p11
s.